// Edge and graph contracts.

import { z } from "zod";
import { ArtifactIdSchema, PaperIdsSchema } from "./common.ts";
import { OccurrenceRoleSchema } from "./occurrence.ts";
import { PaperProfileSchema } from "./paper.ts";

/**
 * Aggregation of all occurrences between one citing paper and one
 * cited paper under a given claim. Keeps the full occurrence trail
 * so any audit can drill back to the individual judgments.
 */
export const EdgeBundleSchema = z.object({
  edgeId: ArtifactIdSchema,
  claimId: ArtifactIdSchema,
  citingPaperId: ArtifactIdSchema,
  citedPaperId: ArtifactIdSchema,
  dominantRole: OccurrenceRoleSchema,
  occurrenceIds: z.array(ArtifactIdSchema),
  roleCounts: z.record(OccurrenceRoleSchema, z.number().int().nonnegative()),
  confidence: z.number().min(0).max(1),
  mixedSignal: z.boolean(),
  inventionTypes: z.array(z.string()).default([]),
  inventionCounts: z.record(z.string(), z.number().int().nonnegative()).default({}),
  /**
   * Per-subclaim role breakdown, populated when occurrences on this
   * edge carry `subclaimIds`. Outer key = subclaim id from the claim
   * pack; inner record = role → count.
   */
  rolesBySubclaim: z
    .record(z.string(), z.record(OccurrenceRoleSchema, z.number().int().nonnegative()))
    .default({}),
});
export type EdgeBundle = z.infer<typeof EdgeBundleSchema>;

export const GraphNodeSchema = z.object({
  paperId: ArtifactIdSchema,
  profile: PaperProfileSchema,
  year: z.number().int(),
  title: z.string(),
  authors: z.array(z.string()),
  venue: z.string().optional(),
  ids: PaperIdsSchema,
  retracted: z.boolean().optional(),
});
export type GraphNode = z.infer<typeof GraphNodeSchema>;

/**
 * One analysis result, keyed by the analysis id declared in the
 * resolved claim pack. `value` is null when denominators are too
 * sparse. `label` is the display string pipeline-generated from the
 * template + taxonomy group; no claim-specific string appears here.
 */
export const AnalysisResultSchema = z.object({
  id: z.string(),
  template: z.string(),
  params: z.record(z.string(), z.any()),
  label: z.string(),
  value: z.number().nullable(),
  denominator: z.number().int().nonnegative().optional(),
  scope: z.string().optional(),   // subclaim id when the analysis is scoped
});
export type AnalysisResult = z.infer<typeof AnalysisResultSchema>;

/**
 * Whole-graph snapshot that the renderer consumes.
 *
 * `analyses` is a flat dictionary keyed by the id generated by the
 * resolver (e.g. `authority-top5`, `echo-amplifier`,
 * `invention-retraction-blindness`). Subclaim-scoped entries carry a
 * `scope: <subclaimId>` field and are keyed as `<id>@<scope>`
 * (e.g. `critique-starvation@sc1`).
 */
export const GraphBundleSchema = z.object({
  graphId: ArtifactIdSchema,
  claimId: ArtifactIdSchema,
  runId: z.string(),
  papers: z.array(GraphNodeSchema),
  edges: z.array(EdgeBundleSchema),
  orphanPaperIds: z.array(ArtifactIdSchema),
  analyses: z.record(z.string(), AnalysisResultSchema).default({}),
  // Global supportive / critical edge totals. Kept outside analyses so
  // the UI can always show denominators.
  edgeTotals: z.object({
    supportive: z.number().int().nonnegative(),
    critical: z.number().int().nonnegative(),
    neutral: z.number().int().nonnegative(),
    mixed: z.number().int().nonnegative(),
    unclear: z.number().int().nonnegative(),
  }),
  authority: z.array(
    z.object({
      paperId: ArtifactIdSchema,
      authorityScore: z.number().min(0).max(1),
      isAuthority: z.boolean(),
      supportiveInDegree: z.number().int().nonnegative(),
      totalInDegree: z.number().int().nonnegative(),
      pageRank: z.number(),
    }),
  ),
});
export type GraphBundle = z.infer<typeof GraphBundleSchema>;
